### ISSUE TITLE
FileNotFoundError : No such file or directory : global_calib.txt

### ISSUE THREAD

**Issue by huangchun12** [ruhyadi/yolo3d-lightning#19]
@ruhyadi Hello!
I have tried to reproduce the actual content of your last article, YOLO3D, and it seems that it can only show the cars and cannot show the pedestrian 3D box. Please share how to achieve it, thank you.
I tried to reproduce yolo3d-lightning run inference.py and found two files were missing, /data/demo/images and /data/global_calib.txt. Could you please share how to achieve it or how to get it? 
Thank you!

**Comment by shona-x** [comment]
@huangchun12 
You can create /data/demo/images folder in your project structure and insert images which you need to evaluate. 

Here is the calibration file I used to run inference. Seems it giving fare results. You can give a try. 
[global_calib.txt](https://github.com/ruhyadi/yolo3d-lightning/files/10833730/global_calib.txt)

**Comment by ruhyadi** [comment]
Thanks for the answer @shehan1995.
I'm really busy right now. But by the end of May I hope to tidy up this repository.

I think the question has been answered, I will close this issue. Don't hesitate to create another issue if you have something to ask.
