### ISSUE TITLE
Kitti results 

### ISSUE THREAD

**Issue by starlipernl** [ruhyadi/yolo3d-lightning#34]
Can you please publish in the readme the Kitti validation and test metrics for the models in this repository?

**Comment by ruhyadi** [comment]
You can see the result from release: [v0.6](https://github.com/ruhyadi/yolo3d-lightning/releases/tag/v0.6).
There is one thing you need to know that, I did not arrange the result dataset according to the KITTI standard, so maybe these values do not reflect the actual results.
