### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for RegressorModel

### ISSUE THREAD

**Issue by LordonCN** [ruhyadi/yolo3d-lightning#54]
After  command `python scripts/get_weights.py` I got regressor_resnet18.pt but inference failed, pls help

**Comment by LordonCN** [comment]
size mismatch for net.orientation.0.weight: copying a param with shape torch.Size([256, 25088]) from checkpoint, the shape in current model is torch.Size([256, 28224]).

**Comment by upper127** [comment]
how to do？
