### ISSUE TITLE
模型推理改进

### ISSUE THREAD

**Issue by guo-pu** [ruhyadi/yolo3d-lightning#65]
您好，模型在推理时是2阶段的，先“检测”出目标的2d信息，再“回归”3d信息，最终结合几何约束生成3D框信息。
在回归推理时，对每个检测出来的物体，单独进行回归，这样会存在一个隐患问题：
当物体数量增多，回归推理时间成倍增加。

我在想能不能把所有检测出来的物体，统一整合到单张图中，这样回归推理的时间是固定的，并提升推理速度。

**Comment by guo-pu** [comment]
或者可以改进yolov5的检测头，在原来的检测2d框位置和类别，添加并行分支（3d尺寸、朝向等），实现一阶段模型推理

**Comment by guo-pu** [comment]
close

**Comment by LordonCN** [comment]
> 您好，模型在推理时是2阶段的，先“检测”出目标的2d信息，再“回归”3d信息，最终结合几何约束生成3D框信息。 在回归推理时，对每个检测出来的物体，单独进行回归，这样会存在一个隐患问题： 当物体数量增多，回归推理时间成倍增加。
> 
> 我在想能不能把所有检测出来的物体，统一整合到单张图中，这样回归推理的时间是固定的，并提升推理速度。

It's true that when the number of obstacles increases sharply, the inference time will significantly increase. You can use multi batch methods for parallel inference, which can effectively improve model efficiency.
