### ISSUE TITLE
weights/get_regressor_weights.py

### ISSUE THREAD

**Issue by desmondkr** [ruhyadi/yolo3d-lightning#70]
I am not able to access the regressor weights:

wandb: ERROR project 'yolo3d-regressor' not found under entity '3ddetection'

**Comment by ruhyadi** [comment]
Sorry for your inconvenience mate,
You can find the weight in the release page
https://github.com/ruhyadi/yolo3d-lightning/releases/tag/v0.6

I wish I have more time to fix this repo

**Comment by desmondkr** [comment]
Thank you!
